version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - mvn clean install -DskipTests

test_script:
  - mvn clean install

branches:
  only:
  - master
  - develop
  - /^feature_.*$/

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
